name: Android Build

on:
  push:
    branches:
      - actions-test
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Ionic
        uses: coturiv/setup-ionic@v1.0.0
      - name: Install dependencies
        run: |
          sudo npm install
      - name: Build
        run: |
          sudo ionic cordova build android
