name: Android Build

on:
  push:
    branches:
      - actions-test
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use coturiv/setup-ionic
      uses: coturiv/setup-ionic@v1
    - name: Build
      run: ionic cordova build android --prod
    - name: Upload app
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk