name: Ionic CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/android-ndk-toolchain-setup@v0.1
      with: 
        api: '21'
        arch: 'arm'
        install-location: 'toolchains'
        force: true
    - name: Install Cordova & Ionic
      run: | 
        sudo npm i -g cordova
        sudo npm i -g @ionic/cli
    - name: Build Android with Ionic
      run: |
        sudo npm install
        sudo ionic cordova build android
