name: Ionic CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install Corodva & Ionic
      run: | 
        npm i -g cordova
        npm i -g @ionic/cli
    - name: Build Android with Ionic
      run: ionic cordova build android
